# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=50)),
                ('search_term', models.CharField(max_length=50)),
                ('dog_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Dog')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('question_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.BooleanField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('yes_list', models.CharField(max_length=128)),
                ('no_list', models.CharField(max_length=128)),
                ('suggested_dog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Dog')),
            ],
        ),
        migrations.AddField(
            model_name='dogtag',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tag'),
        ),
    ]
