# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tag_tag_search_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='exercise',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='grooming',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='group',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='lifespan',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='locality',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='size',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='weight',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
