# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160404_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='good_for_allergies',
            field=models.CharField(default='Bad', max_length=50),
            preserve_default=False,
        ),
    ]
