# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-17 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_dog_good_for_allergies'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dog_img',
            field=models.CharField(default='placeholder.jpg', max_length=50),
            preserve_default=False,
        ),
    ]
