# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_dog_dog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dog_desc',
            field=models.CharField(max_length=1000),
        ),
    ]
